### PR TITLE
Add missing dependency yaml to requirements.txt

### PR DESCRIPTION
**Pull request by alerque**
Imported in pantable2csv.py

### CODE REVIEW

**Comment by ickc** [comment]
panflute depends on YAML so depending on panflute would automatically depends on YAML.

**Comment by alerque** [comment]
Please reconsider this. Yes the panflute package also depends on YAML because it calls it, but **this package's code** also imports and uses `yaml` directly. If you were only calling a panflute function and yaml was getting loaded incidentally to that it would be okay to leave out the dependency (and let the other project pin versions if necessary). As it is **this project** should be calling it out as a dependency and noting which version(s) it is compatible with when necessary.

What you are suggesting is called a [Transitive dependency](https://en.wikipedia.org/wiki/Transitive_dependency) ... except that it isn't rightly even transitive in this case because your first party code here is what imports `yaml`.

**Comment by ickc** [comment]
Ok, done!

**Comment by alerque** [comment]
Thanks.

**Pull request merged**
