### PR TITLE
[pantable2csv]: Fixes error when a table doesn't have a header.

### PR DESCRIPTION
**Pull request by reenberg**
The below traceback was returned, due to an empty header element being passed to
`panflute.stringify`.  The idea (according to the code comment above the line in
question -- line 98) is to set this option to True or False depending on whether
there is a header or not.  Thus we just short circuit this and return False if
the `elem.header` value is None.

----------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/venv2/bin/panflute", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/autofilter.py", line 49, in main
    doc = autorun_filters(filters, doc, extra_path, verbose)
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/autofilter.py", line 95, in autorun_filters
    doc = _['main'](doc)
  File "<string>", line 134, in main
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/io.py", line 265, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/io.py", line 246, in run_filters
    doc = doc.walk(action, doc)
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/base.py", line 274, in walk
    ans = list(chain.from_iterable(ans))
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/base.py", line 272, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/base.py", line 269, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/base.py", line 285, in walk
    altered = action(self, doc)
  File "<string>", line 98, in table2csv
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/tools.py", line 212, in stringify
    element.walk(f)
AttributeError: 'NoneType' object has no attribute 'walk'
pandoc: Error running filter panflute
Filter returned error status 1

### CODE REVIEW

**Comment by reenberg** [comment]
Actually I found this when trying to run both pantable and pantable2csv on the same input file, which converted my csv data to a table, without a caption.

**Comment by ickc** [comment]
Interesting. Can you give me a MWE on the error?

I remembered I did something on this case, where it shouldn't cause a problem. Did panflute changes anything?

**Comment by reenberg** [comment]
Hmm looking further into this. It seems i can only reproduce the errors when running the filters through the 
"running filters automatically" feature of panflute.  Meaning after the patch i made for this to work, has been applied.

Running `pandoc -F pantable -F pantable2csv -w markdown /tmp/bar.md` on the following file seems to work just fine:

file bar.md:

``````{.markdown}
---
panflute-filters: [pantable, pantable2csv]
panflute-path: /home/reenberg/src/pantable/pantable
---

```{.table}
1,2,3
```
``````

However running `pandoc -F panflute -w markdown /tmp/bar.md` generates the AttributeError.

If I just run the pantable filter, then i can see that there is actually a difference in the table that is producered.  Running `pandoc -F pantable -w markdown /tmp/bar.md`:

```{.markdown}
  --- --- ---
  1   2   3
  --- --- ---


```

However `pandoc -F panflute -w markdown /tmp/bar.md` with an updated panflute-filters results in:

```{.markdown}
  ------------------------ ------------------------ ------------------------
  1                        2                        3
  ------------------------ ------------------------ ------------------------


```
Which can be converted fine by only running the panflute2csv filter in both of the mentioned ways.

Thus I can only conclude that panflute must be doing something special (wrong?) when running multiple filters automatically

**Comment by reenberg** [comment]
The following works fine.

```{.markdown}
---
panflute-filters: [pantable2csv, pantable, pantable2csv]
panflute-path: /home/reenberg/src/pantable/pantable
---

  ------------------------ ------------------------ ------------------------
  1                        2                        3
  ------------------------ ------------------------ ------------------------

```

I can't see that the issue should be with panflute, since this works.

```
---
panflute-filters: [pantable2csv]
panflute-path: /home/reenberg/src/pantable/pantable
---

  ------------------------ ------------------------ ------------------------
  1                        2                        3
  ------------------------ ------------------------ ------------------------

```
will generate 


```````
``` {.table}
---
alignment: LLL
header: false
markdown: true
table-width: 0
width: [0, 0, 0]
---
1,2,3
```
```````

which when adding `panflute-filters: [pantable, pantable2csv]` will throw the error.

**Comment by reenberg** [comment]
Adding some debug code to line 212 of panflute/tools.py (right before the call to `element.walk(f)` which throws the error will produce the following:

1. When called `pandoc -F pantable -F pantable2csv -w markdown /tmp/bar.md` it produces:
    ````{.python}
    2csv elem: <class 'panflute.elements.Table'> Table(TableRow(TableCell(Para(Str(1))) TableCell(Para(Str(2))) TableCell(Para(Str(3)))); alignment=[u'AlignLeft', u'AlignLeft', u'AlignLeft'], width=[0, 0, 0], rows=1, cols=3)
    2csv header: <class 'panflute.elements.TableRow'> TableRow(TableCell() TableCell() TableCell())
    panflute element: <class 'panflute.elements.TableRow'> TableRow(TableCell() TableCell() TableCell())
    ````
2. When called `pandoc -F panflute -w markdown /tmp/bar.md`  it produces the following

    ```{.python}
    panflute element: <class 'panflute.elements.MetaInlines'> MetaInlines(Str(/home/reenberg/src/pantable/pantable))
    panflute element: <class 'panflute.elements.MetaInlines'> MetaInlines(Str(pantable))
    panflute element: <class 'panflute.elements.MetaInlines'> MetaInlines(Str(pantable2csv))
    2csv elem: <class 'panflute.elements.Table'> Table(TableRow(TableCell(Para(Str(1))) TableCell(Para(Str(2))) TableCell(Para(Str(3)))); alignment=[u'AlignLeft', u'AlignLeft', u'AlignLeft'], width=[0.0, 0.0, 0.0], rows=1, cols=3)
    2csv header: <type 'NoneType'> None
    panflute element: <type 'NoneType'> None
    Failed to run filter: pantable2csv
    [...]
    ```
So clearly the `elem.header` value is different.  I suspect that when running 1) pandoc or panflute does something to the returned AST (normalisation?), and thus inserts an empty TableRow, where as running 2) the pantable2csv filter receives the AST directly as changed by pantable, thus the TableRow is not inserted in `elem.header` (for elem being a Table).

That leaves the question to be whether or not elem.header (for elem being a Table) must contain an empty TableRow or whether it is acceptable that it is None.

Looking at the pandoc AST didn't really clarify whether the header list could be an empty list or needs to be a list of empty cells.

**Comment by ickc** [comment]
@sergiocorreia, @reenberg found a bug that only happens when autofilter is used. Do you have any idea what might be the cause of the problem here?

**Comment by sergiocorreia** [comment]
I went through the thread, and my guess is that pandoc might be "fixing" something (when the two filters are run sequentially) that Pandoc doesn't. For instance, maybe it is checking if the table body is empty and there is a header, in which case the header becomes the first (and only) row of the table body.

I would have to dig more to see if that's the case (and then, the best way to prevent issues like this).

**Comment by ickc** [comment]
I'll also take a look into this when I've the time. Seems very interesting. I'll not have time at least until the weekend though. Thanks all.

**Comment by ickc** [comment]
> I'll not have time at least until the weekend though.

LOL. My next weekend is 14 months later. Sorry I was busy and didn't have much time for weekend projects...

I will merge it soon.

**Comment by reenberg** [comment]
Sorry. Have been way busy and for some reason didn't notice the mails.

Seems that you fixed it.

**Pull request merged**
